compiler_type = "ido"

[preserve_macros]
"GET_ACTOR.*" = "struct Actor*"
NORM_ANGLE = "void"
RAD2DEG = "int"
DEG2RAD = "int"
".*sets" = "void"
SQ = "void"
NULL = "int"
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"gDma.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_IM_FMT_.*" = "int"
"G_TX_.*" = "int"
"G_[AC]C.*" = "int"